### Create a account
POST http://localhost:8080/account HTTP/1.1
Content-Type: application/json

{
    "first_name": "Maria",
    "last_name": "Maia"
}

### List all accounts
GET http://localhost:8080/account HTTP/1.1


### Get account by id
GET http://localhost:8080/account/1 HTTP/1.1


### Update account
PUT http://localhost:8080/account/1 HTTP/1.1
Content-Type: application/json

{
    "first_name": "Elieudo",
    "last_name": "Rocha"
}

### Delete account
DELETE http://localhost:8080/account/34 HTTP/1.1


### Transfer
PATCH http://localhost:8080/transfer
Content-Type: application/json

{
    "from_account_id": 1,
    "to_account_id": 36,
    "amount": 10
}


### SignIn
POST http://localhost:8080/signin HTTP/1.1
Content-Type: application/json

{
    "account_number": 6265581263449925819,
    "password": "123456"
}